/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formGiaoDien;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Borrower;
import model.Loan;
import javax.swing.JOptionPane;

/**
 *
 * @author NCpc
 */
public class Form_QuanLyMuonTra extends javax.swing.JFrame {

    List<Loan> loanList = new ArrayList<>();
    List<Book> bookList = new ArrayList<>();
    List<Borrower> borrowerList = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model1 = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();

    /**
     * Creates new form Form_QuanLyMuonTra
     */
    public Form_QuanLyMuonTra() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tbMuonTra.getModel();
        model1 = (DefaultTableModel) tbThongKeSach.getModel();
        model2 = (DefaultTableModel) tbThongKeThanhVien.getModel();
        showAll();
        bookStatistics();
        memberStatistics();

    }

    public void showAll() {
        loanList = Loan.getAllLoan();
        model.setRowCount(0);
        loanList.forEach(ln -> {
            model.addRow(new Object[]{model.getRowCount() + 1,
                ln.getMaThanhVien(),
                ln.getTenThanhVien(),
                ln.getMaSach(),
                ln.getTenSach(),
                ln.getNgayMuon(), ln.getNgayTra(), ln.getPeriod()});
        });
        tbMuonTra.setModel(model);
    }

    public void bookStatistics() {
        bookList = Book.findAll();
        model1.setRowCount(0);
        bookList.forEach(bk -> {
            model1.addRow(new Object[]{model1.getRowCount() + 1,
                bk.getMaSach(), bk.getTenSach(),
                bk.getConLai()});
        });
        tbThongKeSach.setModel(model1);
    }

    public void memberStatistics() {
        borrowerList = Borrower.findAllBorrower();
        model2.setRowCount(0);
        borrowerList.forEach(br -> {
            model2.addRow(new Object[]{model2.getRowCount() + 1,
                br.getMaThanhVien(), br.getTenThanhVien(),
                br.getChucVu()});
        });
        tbThongKeThanhVien.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMuonTra = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfMaTV = new javax.swing.JTextField();
        tfMaSach = new javax.swing.JTextField();
        tfNgayMuon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNgayTra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnMuonMoi = new javax.swing.JButton();
        btnTraSach = new javax.swing.JButton();
        tfTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbThongKeSach = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbThongKeThanhVien = new javax.swing.JTable();
        btnTimKiemMS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ MƯỢN-TRẢ SÁCH");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        tbMuonTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã TV", "Tên TV", "Mã sách", "Tên sách", "Ngày mượn", "Ngày trả", "Tổng (ngày)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMuonTra);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã TV");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mã sách");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ngày mượn");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Ngày trả");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addComponent(tfNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfMaSach, tfMaTV, tfNgayMuon});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jLabel8))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, tfMaTV});

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 153, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave);

        btnMuonMoi.setText("Mượn sách");
        btnMuonMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonMoiActionPerformed(evt);
            }
        });
        jPanel5.add(btnMuonMoi);

        btnTraSach.setText("Trả sách");
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });
        jPanel5.add(btnTraSach);

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 255));
        btnTimKiem.setText("Tìm Mã TV");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel7.add(btnReset);

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 0, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel7.add(btnThoat);

        tbThongKeSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sách", "Tên Sách", "SL(còn lại)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbThongKeSach);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THỐNG KÊ SÁCH");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("THỐNG KÊ THÀNH VIÊN");

        tbThongKeThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã TV", "Tên Thành Viên", "Chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbThongKeThanhVien);

        btnTimKiemMS.setBackground(new java.awt.Color(204, 255, 255));
        btnTimKiemMS.setText("Tìm mã sách");
        btnTimKiemMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemMSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(629, 629, 629))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTimKiem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTimKiemMS))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTimKiemMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Form_HomeScreen().setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnMuonMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonMoiActionPerformed

        int slIndex1 = -1, slIndex2 = -1;
        slIndex1 = tbThongKeSach.getSelectedRow();
        slIndex2 = tbThongKeThanhVien.getSelectedRow();

        while (slIndex1 == -1 || slIndex2 == -1) {
            JOptionPane.showMessageDialog(this, "Chọn thông tin ở bảng bên phải");
            return;
        }
        if (slIndex1 != -1 && slIndex2 != -1) {

            bookList = Book.findAll();
            borrowerList = Borrower.findAllBorrower();
            Book bk = bookList.get(slIndex1);
            tfMaSach.setText(bk.getMaSach());
            Borrower br = borrowerList.get(slIndex2);
            tfMaTV.setText(br.getMaThanhVien());
            JOptionPane.showMessageDialog(this, "Nhập ngày mượn / trả và chọn Save");
            tfNgayMuon.requestFocus();
        }

    }//GEN-LAST:event_btnMuonMoiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfMaSach.setText("");
        tfMaTV.setText("");
        tfNgayMuon.setText("");
        tfNgayTra.setText("");
        tfTimKiem.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    public void LuuTT() {
        String maTV = tfMaTV.getText();
        String maSach = tfMaSach.getText();
        String ngayMuon = tfNgayMuon.getText();
        String ngayTra = tfNgayTra.getText();
        if (ngayMuon.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ngày mượn đang trống", "Error", JOptionPane.ERROR_MESSAGE);
            tfNgayMuon.requestFocus();
        } else if (ngayTra.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ngày trả đang trống", "Error", JOptionPane.ERROR_MESSAGE);
            tfNgayTra.requestFocus();
        }
        Loan loan = new Loan();
        loan.setMaThanhVien(maTV);
        loan.setMaSach(maSach);
        
        Pattern pattern = Pattern.compile("^[0-9]{4}[-][0-9]{2}[-][0-9]{2}$"); // "\\d{4}[-]\\d{1,2}[-]\\d{1,2}"
        Matcher matcher = pattern.matcher(ngayMuon);
        Matcher matcher1 = pattern.matcher(ngayTra);
        if(!matcher.find()){
            JOptionPane.showMessageDialog(null, "Ngày mượn sai định dạng yyyy-MM-dd");
            tfNgayMuon.setText("");
            tfNgayMuon.requestFocus();
        }
        else if(!matcher1.find()){
            JOptionPane.showMessageDialog(null, "Ngày trả sai định dạng yyyy-MM-dd");
            tfNgayTra.setText("");
            tfNgayTra.requestFocus();
        }
        
        DateFormat dfYMD = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date day1 = dfYMD.parse(ngayMuon);
            loan.setNgayMuon(day1);
        } catch (ParseException ex) {
            Logger.getLogger(Form_QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
            
            tfNgayMuon.requestFocus();
        }
        try {
            Date day2 = dfYMD.parse(ngayTra);
            loan.setNgayTra(day2);
        } catch (ParseException ex) {
            Logger.getLogger(Form_QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
            
            tfNgayTra.requestFocus();
        }
        Loan.create(loan);
        showAll();
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String ms = tfMaSach.getText();
        String maTV = tfMaTV.getText();
        String ngayMuon = tfNgayMuon.getText();
        String ngayTra = tfNgayTra.getText();
        
        if(ms.isEmpty() || maTV.isEmpty() || ngayMuon.isEmpty() || ngayTra.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nhập đầy đủ TT trước khi LƯU", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String idThanhVien = tfMaTV.getText();
        loanList = Loan.searchByBorrowerID(idThanhVien);
        int cnt = 0, cnt1 = 0;
      
        if (loanList.isEmpty()) {
            int i = JOptionPane.showConfirmDialog(this, "Lưu thông tin?", "Question?", JOptionPane.YES_NO_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                LuuTT();
                bookStatistics();
            }
        } else {
            if (idThanhVien.startsWith("SV")) {
                if (loanList.size() >= 5) {
                    JOptionPane.showMessageDialog(this, "Yêu cầu trả sách trước khi mượn thêm");
                } else {
                    int i = JOptionPane.showConfirmDialog(this, "Lưu thông tin?", "Question?", JOptionPane.YES_NO_OPTION);
                    if (i == JOptionPane.YES_OPTION) {
                        LuuTT();
                        bookStatistics();
                    }
                }
            } else {
                if (loanList.size() >= 7) {
                    JOptionPane.showMessageDialog(this, "Yêu cầu trả sách trước khi mượn thêm");
                } else {
                    int i = JOptionPane.showConfirmDialog(this, "Lưu thông tin?", "Question?", JOptionPane.YES_NO_OPTION);
                    if (i == JOptionPane.YES_OPTION) {
                        LuuTT();
                        bookStatistics();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String input = tfTimKiem.getText();
        if (input != null) {
            loanList = Loan.searchByBorrowerID(input);
            model.setRowCount(0);
            loanList.forEach(ln -> {
                model.addRow(new Object[]{model.getRowCount() + 1,
                    ln.getMaThanhVien(),
                    ln.getTenThanhVien(),
                    ln.getMaSach(),
                    ln.getTenSach(),
                    ln.getNgayMuon(), ln.getNgayTra(), ln.getPeriod()});
            });
            tbMuonTra.setModel(model);
        } else {
            showAll();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTimKiemMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemMSActionPerformed
        // TODO add your handling code here:
        String input = tfTimKiem.getText();
        if (input != null) {
            loanList = Loan.searchByBookID(input);
            model.setRowCount(0);
            loanList.forEach(ln -> {
                model.addRow(new Object[]{model.getRowCount() + 1,
                    ln.getMaThanhVien(),
                    ln.getTenThanhVien(),
                    ln.getMaSach(),
                    ln.getTenSach(),
                    ln.getNgayMuon(), ln.getNgayTra(), ln.getPeriod()});
            });
            tbMuonTra.setModel(model);
        } else {
            showAll();
        }
    }//GEN-LAST:event_btnTimKiemMSActionPerformed

    public void traSach(String maSach, String maTV) {
        Loan.traSach(maSach, maTV);
        showAll();
    }
    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        // TODO add your handling code here:
        try {
            int select = tbMuonTra.getSelectedRow();
            Loan ln = loanList.get(select);
            String maTV = ln.getMaThanhVien();
            String maSach = ln.getMaSach();
            int tg = ln.getPeriod();
            int tienPhat = 0;
            if (maTV.startsWith("SV")) {
                if (tg > 90) {
                    int kd = JOptionPane.showConfirmDialog(this, "Trả sách?", "Question", JOptionPane.YES_NO_OPTION);
                    if (kd == JOptionPane.YES_OPTION) {
                        traSach(maSach, maTV);
                        tienPhat = (tg - 90) * 1000;
                        JOptionPane.showMessageDialog(this, "Bị phạt " + tienPhat + " vnd vì trả muộn " + (tg - 90) + " ngày!", "Wanring", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    int kd = JOptionPane.showConfirmDialog(this, "Trả sách?", "Question", JOptionPane.YES_NO_OPTION);
                    if (kd == JOptionPane.YES_OPTION) {
                        traSach(maSach, maTV);
                    }
                }
            } else {
                if (tg > 365) {
                    int kd = JOptionPane.showConfirmDialog(this, "Trả sách?", "Question", JOptionPane.YES_NO_OPTION);
                    if (kd == JOptionPane.YES_OPTION) {
                        traSach(maSach, maTV);
                        tienPhat = (tg - 365) * 1000;
                        JOptionPane.showMessageDialog(this, "Bị phạt " + tienPhat + " vnd vì trả muộn " + (tg - 365) + " ngày!", "Wanring", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    int kd = JOptionPane.showConfirmDialog(this, "Trả sách?", "Question", JOptionPane.YES_NO_OPTION);
                    if (kd == JOptionPane.YES_OPTION) {
                        traSach(maSach, maTV);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chọn TT ở bảng trên rồi nhấn TRẢ SÁCH");
        }


    }//GEN-LAST:event_btnTraSachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_QuanLyMuonTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMuonMoi;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiemMS;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbMuonTra;
    private javax.swing.JTable tbThongKeSach;
    private javax.swing.JTable tbThongKeThanhVien;
    private javax.swing.JTextField tfMaSach;
    private javax.swing.JTextField tfMaTV;
    private javax.swing.JTextField tfNgayMuon;
    private javax.swing.JTextField tfNgayTra;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
